server.port: 8090

--- ###########################################################################

spring.profiles: integration

--- ###########################################################################

spring.profiles: local

--- ###########################################################################

spring.profiles: staging

--- ###########################################################################

spring.profiles: prod
